/* MAELIE — mini-panier latéral, branché sur le panier existant */
(()=>{
  'use strict';
  if(!window.MAELIE){console.warn('MAELIE cart drawer: core.js doit être chargé avant cart-drawer.js');return;}
  const FREE_SHIPPING=80;
  const money=n=>typeof MAELIE.money==='function'?MAELIE.money(n):new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(n)||0);
  const create=()=>{if(document.querySelector('.ma-cart-drawer'))return;const o=document.createElement('div');o.className='ma-cart-overlay';o.setAttribute('aria-hidden','true');const d=document.createElement('aside');d.className='ma-cart-drawer';d.setAttribute('aria-hidden','true');d.setAttribute('aria-label','Mini panier');d.innerHTML=`<header class="ma-cart-header"><div><span class="ma-cart-header__eyebrow">MAELIE</span><h2 class="ma-cart-header__title">Votre panier <span class="ma-cart-header__count" data-drawer-count>0 article</span></h2></div><button type="button" class="ma-cart-close" data-cart-drawer-close aria-label="Fermer le panier">×</button></header><div class="ma-cart-content" data-cart-drawer-content></div><footer class="ma-cart-footer" data-cart-drawer-footer></footer>`;document.body.append(o,d)};
  const data=()=>{const items=MAELIE.cart();let subtotal=0,quantity=0;items.forEach(x=>{const p=MAELIE.product(x.id);if(p){subtotal+=Number(p.price)*Number(x.quantity);quantity+=Number(x.quantity)}});const coupon=typeof MAELIE.read==='function'?MAELIE.read(MAELIE.COUPON,''):'';const discount=coupon==='MAELIE10'?subtotal*.1:0;const shipping=items.length?(subtotal-discount>=FREE_SHIPPING?0:4.9):0;return{items,quantity,subtotal,discount,shipping,total:subtotal-discount+shipping,coupon}};
  const render=()=>{create();const c=document.querySelector('[data-cart-drawer-content]'),f=document.querySelector('[data-cart-drawer-footer]'),n=document.querySelector('[data-drawer-count]'),d=data();n.textContent=`${d.quantity} ${d.quantity>1?'articles':'article'}`;if(!d.items.length){c.innerHTML=`<div class="ma-cart-empty"><div class="ma-cart-empty__icon">♡</div><h3>Votre panier est vide</h3><p>Découvrez les pièces imaginées par MAELIE et laissez-vous inspirer.</p><a href="boutique.html" class="ma-cart-empty__button" data-cart-close-link>Découvrir la boutique</a></div>`;f.innerHTML='';return}c.innerHTML=d.items.map((x,i)=>{const p=MAELIE.product(x.id);if(!p)return'';const total=Number(p.price)*Number(x.quantity);return `<article class="ma-cart-item" style="animation-delay:${i*60}ms"><a href="product.html?slug=${encodeURIComponent(p.slug)}" class="ma-cart-item__image" data-cart-close-link><img src="${p.img}" alt="${p.name}"></a><div class="ma-cart-item__info"><span class="ma-cart-item__category">${p.cat||'MAELIE'}</span><h3 class="ma-cart-item__name"><a href="product.html?slug=${encodeURIComponent(p.slug)}" data-cart-close-link>${p.name}</a></h3><span class="ma-cart-item__price">${money(p.price)}</span><div class="ma-cart-quantity"><button type="button" data-drawer-minus="${p.id}" aria-label="Diminuer">−</button><span class="ma-cart-quantity__number">${x.quantity}</span><button type="button" data-drawer-plus="${p.id}" aria-label="Augmenter">+</button></div><strong class="ma-cart-item__total">${money(total)}</strong></div><button type="button" class="ma-cart-item__remove" data-drawer-remove="${p.id}" aria-label="Supprimer ${p.name}">×</button></article>`}).join('');const amount=Math.max(0,d.subtotal-d.discount),progress=Math.min(100,amount/FREE_SHIPPING*100);const shippingText=d.shipping===0?'<strong>Livraison offerte ✦</strong>':`Plus que <strong>${money(FREE_SHIPPING-amount)}</strong> pour la livraison offerte`;f.innerHTML=`<div class="ma-cart-shipping"><div class="ma-cart-shipping__text"><span>${shippingText}</span></div><div class="ma-cart-shipping__bar"><div class="ma-cart-shipping__progress" style="width:${progress}%"></div></div></div><div class="ma-cart-total"><span>Total</span><strong>${money(d.total)}</strong></div><div class="ma-cart-actions"><a href="panier.html" class="ma-cart-button ma-cart-button--outline" data-cart-close-link>Voir mon panier</a><a href="commande.html" class="ma-cart-button ma-cart-button--dark" data-cart-close-link>Passer la commande</a></div><p class="ma-cart-secure">Paiement sécurisé · Retours sous 14 jours</p>`};
  const open=()=>{create();render();const d=document.querySelector('.ma-cart-drawer'),o=document.querySelector('.ma-cart-overlay');requestAnimationFrame(()=>{d.classList.add('is-open');o.classList.add('is-open')});d.setAttribute('aria-hidden','false');o.setAttribute('aria-hidden','false');document.body.classList.add('ma-cart-lock')};
  const close=()=>{const d=document.querySelector('.ma-cart-drawer'),o=document.querySelector('.ma-cart-overlay');if(!d)return;d.classList.remove('is-open');o&&o.classList.remove('is-open');d.setAttribute('aria-hidden','true');o&&o.setAttribute('aria-hidden','true');document.body.classList.remove('ma-cart-lock')};
  document.addEventListener('click',e=>{const plus=e.target.closest('[data-drawer-plus]'),minus=e.target.closest('[data-drawer-minus]'),remove=e.target.closest('[data-drawer-remove]');if(plus||minus){e.preventDefault();const id=Number((plus||minus).dataset[plus?'drawerPlus':'drawerMinus']),row=MAELIE.cart().find(x=>Number(x.id)===id);if(row)MAELIE.qty(id,Number(row.quantity)+(plus?1:-1));return}if(remove){e.preventDefault();const id=Number(remove.dataset.drawerRemove),item=remove.closest('.ma-cart-item');if(item){item.style.transition='opacity .22s ease,transform .22s ease';item.style.opacity='0';item.style.transform='translateX(25px)'}setTimeout(()=>MAELIE.remove(id),180);return}if(e.target.closest('[data-cart-drawer-close]')){e.preventDefault();close();return}if(e.target.closest('[data-cart-close-link]'))close();if(e.target.closest('.ma-cart-overlay'))close()});
  document.addEventListener('click',e=>{const b=e.target.closest('button[aria-label="Mon panier"],a[aria-label="Mon panier"],[data-cart-open]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();open()},true);
  document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
  window.addEventListener('maelie:cart',()=>{const d=document.querySelector('.ma-cart-drawer');if(d&&d.classList.contains('is-open'))render()});
  document.addEventListener('DOMContentLoaded',create);
  MAELIE.openCartDrawer=open;MAELIE.closeCartDrawer=close;
})();
